### ISSUE TITLE
Does not work with password salt!

### ISSUE THREAD

**Issue by KaeTuuN** [viruzx/Owncloud-Registration#1]
Is there a way to fix that? I want to use this App, but I need the salt for security reasons.

**Comment by vezaynk** [comment]
I would gladly fix it! However I have no idea how the password is salted during authentication. If you could tell me the file that does this, that would be awesome and would be fixed within a day.

**Comment by vezaynk** [comment]
Closed due to inactivity. If you have something to say on the matter, create a new issue.
