### ISSUE TITLE
How do i actually use this?

### ISSUE THREAD

**Issue by Weuxel** [viruzx/Owncloud-Registration#2]
I did what was told on http://knyz.org/blog/owncloud-registration-fixed/.
But what next? How do i actually use this app?

Regards,
Norman

**Comment by vezaynk** [comment]
Could you please be more specific on what is not working or what you are trying to accomplish?

**Comment by Weuxel** [comment]
How do i integrate this so it is actually usable in Owncloud? Do i have to insert the code block in demo.html manually?

**Comment by vezaynk** [comment]
Once you have configured `config.php`, upload all those files to anywhere on your server. `demo.html` is a basic usable form to submit data required to register the user and you don't really need it after you made sure everything works smoothly.

**Comment by Weuxel** [comment]
"Once you have configured config.php, upload all those files to anywhere on your server."

This sounds like that is the only thing needed. But surely there must be done something to tell Owncloud to use it.

**Comment by vezaynk** [comment]
Aaah, I see the issue! The script does not work like an app would (as in you do _not_ put it in the /apps/ directory or anything of sorts). The script works completely separately from ownCloud.

All it does it create a new user in your database for ownCloud to use via SQL.
That clear up any confusion?

**Comment by Weuxel** [comment]
Yes. Thank you.

**Comment by bl4ckb0n3** [comment]
I can't access http://knyz.org/blog/owncloud-registration-fixed/  ....how can i get it working ???

**Comment by vezaynk** [comment]
@bl4ckb0n3 You should have made a new issue for this. I am having trouble with that since a while.

Since you need it, I will get that up soon. I will contact you then.

**Comment by bl4ckb0n3** [comment]
I know this about other pepole who have made something like this.  there a
sql injection vulnerability with most of script pepole write ... So If you
give me the way to install it i will help you to make it working if i can .
I dont want to guest how to do it ... so im sure you have beter skill than
me with programing but if you want me to  give you my support help me and i
will do all i can do to make it working !!

cordially
Bl4ckb0n3

2015-06-03 1:01 GMT-04:00 Slava Knyazev notifications@github.com:

**Comment by vezaynk** [comment]
The issue is that I messed up my migration due to having a load of 
pressure dropped on me and needed to get a server up and running within 
hours while I usually take a couple of days to make sure everything 
works smoothly so my Ghost Blog doesn't work as it should.

I will get it running by the end of the week, hopefully.

**Comment by bl4ckb0n3** [comment]
Ok good luck and thank you for answered me :-) i will wait for your news

**Comment by vezaynk** [comment]
@bl4ckb0n3 ~~Umm... sir... I just realized I messed up with that a bit... I lost my backups...

Still the config.php file is pretty strait-forward (At least I remember it being..) so you might be able to figure it out.~~

Edit: Apparently I had the backups of my backups backed up. Disregard

**Comment by vezaynk** [comment]
Okay... I got this up in a rush, 30 minutes late, not fully functional but the text is there.

http://nodejs-knyz.rhcloud.com/php-pseudo-randomness-that-works/

Enjoy.
